version: "3.4"

services:
  start-website:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: website
    container_name: website
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - 8081:80
